version: "3.0"

services:
  _defaults: &DEFAULTS
    image: ruby:alpine
    volumes:
      - .:/app
      - gems:/gems
      - $HOME/.ssh:/root/.ssh
    working_dir: /app
    environment: &ENVIRONMENT
      BUNDLE_JOBS: 4
      BUNDLE_HOME: /gems
      BUNDLE_PATH: /gems
      GEM_HOME: /gems
      GEM_PATH: /gems

  bundle:
    <<: *DEFAULTS
    entrypoint: bundle

  rr:
    <<: *DEFAULTS

volumes:
  gems:
    external: true
